name: uarray
channels:
  - pytorch
  - xnd/label/dev
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - sphinx
  - sphinx_rtd_theme
  - pytest
  - pytest-flake8
  - pytest-cov
  - pytorch-cpu
  - scipy
  - gumath
  - pip:
    - pytest-mypy
